### PR TITLE
Fixed URL Generation Not Taking Forwarded Header Into Account 

### LINKED ISSUE #109: URL Generation Does Not Take Forwarded Header Into Account
Running PREvant behind HTTPS breaking the URLs in the frontend because the [`RequestInfo` construction](https://github.com/aixigo/PREvant/blob/bc93f9ccce110b79a4de24367106a144a9e37bc0/api/src/models/request_info.rs) does not handle this case.

### PR DESCRIPTION
**Pull request by AnumDastgir**
Added and fixed code which takes into account the forwarded headers specifically x-forwarded-host, x-forwarded-proto and x-forwarded port. The url doesn't break any more and works with the required protocols.

Fixes #109

### CODE REVIEW

File: api/src/models/request_info.rs [hunk 1]
```diff
@@ -57,6 +58,11 @@ impl RequestInfo {
         self.base_url.scheme()
     }
 
+    // Returns the forwarded port.
+    pub fn port(&self) -> &str {
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:62]: I think `port`, `scheme`, and `host` are methods that aren't used anywhere (I think I see some compiler warnings all the time). Therefore, I would like to remove them.

File: api/src/models/request_info.rs [hunk 2]
```diff
@@ -32,6 +32,7 @@ use url::Url;
 #[derive(Clone)]
 pub struct RequestInfo {
     base_url: Url,
+    forwarded_port: String,
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:35]: I think it isn't necessary to store this value.

File: api/src/models/request_info.rs [hunk 3]
```diff
@@ -67,16 +73,40 @@ impl<'r> FromRequest<'r> for RequestInfo {
     type Error = ();
 
     async fn from_request(request: &'r Request<'_>) -> request::Outcome<Self, Self::Error> {
-        let hosts: Vec<_> = request.headers().get("host").collect();
+        // Checking if "x-forwarded-host" header is present
+        let forwarded_host = request.headers().get_one("x-forwarded-host");
+        let host = match forwarded_host {
+            Some(proto) => proto.to_string(),
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:79]: Typo?

```suggestion
            Some(host) => host.to_string(),
```

File: api/src/models/request_info.rs [hunk 4]
```diff
@@ -67,16 +73,40 @@ impl<'r> FromRequest<'r> for RequestInfo {
     type Error = ();
 
     async fn from_request(request: &'r Request<'_>) -> request::Outcome<Self, Self::Error> {
-        let hosts: Vec<_> = request.headers().get("host").collect();
+        // Checking if "x-forwarded-host" header is present
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:76]: I think the code tells the reader exactly what it does.

```suggestion
```

Most of the comments do. Please, adjust accordingly and only keep comments that document something that isn't obvious from code.

File: api/src/models/request_info.rs [hunk 5]
```diff
@@ -67,16 +73,40 @@ impl<'r> FromRequest<'r> for RequestInfo {
...
+        let forwarded_host = request.headers().get_one("x-forwarded-host");
+        let host = match forwarded_host {
+            Some(proto) => proto.to_string(),
+            None => request.headers().get_one("host").unwrap().to_string(), // Default to "host" if not present
+        };
 
-        if hosts.len() != 1 {
+        if host == "" {
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:83]: Due to `unwarp().to_string()` in line 80 the code my fail with a panic in the server and the server wouldn't respond with bad request. I would remove this if block and adjust the match above like this:

```rust
        let forwarded_host = request.headers().get_one("x-forwarded-host");
        let host = match forwarded_host {
            Some(host) => host.to_string(),
            None => match request.headers().get_one("host") {
                Some(host) => host.to_string(),
                None => {
                    return Outcome::Failure((Status::BadRequest, ()));
                }
            }
        }
```

This has the advantage of saving a little CPU cycles (because there is no string allocation if there is no host header) and it doesn't panic.

File: api/src/models/request_info.rs [hunk 6]
```diff
@@ -67,16 +73,40 @@ impl<'r> FromRequest<'r> for RequestInfo {
...
-        let url_string = format!("http://{}", hosts[0]);
-        match Url::parse(&url_string) {
-            Ok(url) => return Outcome::Success(RequestInfo { base_url: url }),
-            Err(_) => return Outcome::Failure((Status::BadRequest, ())),
+        // Checking if "x-forwarded-proto" header is present
+        let forwarded_proto_header = request.headers().get_one("x-forwarded-proto");
+        let forwarded_proto = match forwarded_proto_header {
+            Some(proto) => proto.to_string(),
+            None => "http".to_string(), // Default to "http" if not present
+        };
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:92]: I would rewrite this and the match below and use would use [`unwrap_or_else`](https://api.rocket.rs/v0.5-rc/rocket/mtls/oid/asn1_rs/nom/lib/std/option/enum.Option.html#method.unwrap_or_else) because that makes these `// default to … if not present` comments obsolete.

```suggestion
        let forwarded_proto = request.headers().get_one("x-forwarded-proto").map(|proto| proto.to_string()).unwrap_or_else(|| String::from("http"));
```

**Review by schrieveslaach — CHANGES_REQUESTED** [review]
Thanks for tackling #109 and sorry for the confusion with the forwarded vs x-forwarded-* headers.

The approach looks good to me. I suggested minor code improvements. Please, check out my comments.

I was wondering if we should add some [test via Rocket](https://rocket.rs/v0.5-rc/guide/testing/#testing) to ensure that everything keeps working. Ping me via DM to discuss that.

File: examples/Kubernetes/PREvant.yml [hunk 7]
```diff
@@ -65,6 +65,7 @@ metadata:
 spec:
   entryPoints:
     - http
+    - websecure
```
Comment (schrieveslaach) [inline examples/Kubernetes/PREvant.yml:68]: Please, remove that from the examples because it might not work for others.

```suggestion
```

File: api/src/models/request_info.rs [hunk 8]
```diff
@@ -67,16 +45,33 @@ impl<'r> FromRequest<'r> for RequestInfo {
...
+            .headers()
+            .get_one("x-forwarded-port")
+            .map(|port| format!(":{}", port.to_string()))
+            .unwrap_or_else(|| String::from(""));
 
-        let url_string = format!("http://{}", hosts[0]);
-        match Url::parse(&url_string) {
-            Ok(url) => return Outcome::Success(RequestInfo { base_url: url }),
-            Err(_) => return Outcome::Failure((Status::BadRequest, ())),
+        // Constructing URL based on  headers
```
Comment (schrieveslaach) [inline api/src/models/request_info.rs:70]:
```suggestion
```

**Review by schrieveslaach — CHANGES_REQUESTED** [review]
Changes look fine and I appreciate fixing this bug. Please, clean up the suggestion.

**Comment by AnumDastgir** [comment]
> Changes look fine and I appreciate fixing this bug. Please, clean up the suggestion.

Clean up is done.

**Review by schrieveslaach — APPROVED** [review]
Looks good to me now. Please, squash your commit into one before merging.
