### PR TITLE
Replace ShipLift Crate with Bollard as Docker SDK

### LINKED ISSUE #160: PREvant is not Working with Docker Engine 25.0.1
Since Docker Engine 25.0.1 PREvant stops working in some environments with following error when creating a application:

```json
{
  "type": "https://httpstatuses.com/500",
  "status": 500,
  "title": "Internal Server Error",
  "detail": "Cannot interact with infrastructure: Docker Error: invalid type: null, expected a sequence at line 1 column 242"
}
```

Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:52 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:52 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

With `RUST_LOG=trace` reveals that the logging of [this line](https://github.com/aixigo/PREvant/blob/f8c72ba6f3e7e3e5b8ee7d4d06ce9c011e892d74/api/src/infrastructure/docker.rs#L147) seems to be executed but the network creating afterwards fails because there is no network created on the host and no other PREvant specific logs are revealed:

```
[2024-01-25T11:45:35Z TRACE prevant::infrastructure::docker] Resolve network id for test
[2024-01-25T11:45:35Z TRACE hyper::client::conn] client handshake Http1
[2024-01-25T11:45:35Z TRACE hyper::client::client] handshake complete, spawning background dispatcher task
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[2024-01-25T11:45:35Z TRACE tracing::span] encode_headers;
[2024-01-25T11:45:35Z TRACE tracing::span::active] -> encode_headers;
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::role] Client::encode method=GET, body=None
[2024-01-25T11:45:35Z TRACE tracing::span::active] <- encode_headers;
[2024-01-25T11:45:35Z TRACE tracing::span] -- encode_headers;
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::io] flushed 34 bytes
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] Conn::read_head
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::io] received 2248 bytes
[2024-01-25T11:45:35Z TRACE tracing::span] parse_headers;
[2024-01-25T11:45:35Z TRACE tracing::span::active] -> parse_headers;
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::role] Response.parse bytes=2248
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::role] Response.parse Complete(203)
[2024-01-25T11:45:35Z TRACE tracing::span::active] <- parse_headers;
[2024-01-25T11:45:35Z TRACE tracing::span] -- parse_headers;
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::io] parsed 7 headers
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::conn] incoming body is content-length (2045 bytes)
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::decode] decode; state=Length(2045)
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::conn] incoming body completed
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] maybe_notify; read_from_io blocked
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2024-01-25T11:45:35Z TRACE hyper::client::pool] pool dropped, dropping pooled (("unix", 2f7661722f72756e2f646f636b65722e736f636b:0))
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::dispatch] client tx closed
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] State::close_read()
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] State::close_write()
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] shut down IO complete
[2024-01-25T11:45:35Z TRACE hyper::client::conn] client handshake Http1
[2024-01-25T11:45:35Z TRACE hyper::client::client] handshake complete, spawning background dispatcher task
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
[2024-01-25T11:45:35Z TRACE tracing::span] encode_headers;
[2024-01-25T11:45:35Z TRACE tracing::span::active] -> encode_headers;
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::role] Client::encode method=DELETE, body=None
[2024-01-25T11:45:35Z TRACE tracing::span::active] <- encode_headers;
[2024-01-25T11:45:35Z TRACE tracing::span] -- encode_headers;
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::io] flushed 104 bytes
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] Conn::read_head
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::io] received 157 bytes
[2024-01-25T11:45:35Z TRACE tracing::span] parse_headers;
[2024-01-25T11:45:35Z TRACE tracing::span::active] -> parse_headers;
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::role] Response.parse bytes=157
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::role] Response.parse Complete(157)
[2024-01-25T11:45:35Z TRACE tracing::span::active] <- parse_headers;
[2024-01-25T11:45:35Z TRACE tracing::span] -- parse_headers;
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::io] parsed 5 headers
[2024-01-25T11:45:35Z DEBUG hyper::proto::h1::conn] incoming body is empty
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] maybe_notify; read_from_io blocked
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
[2024-01-25T11:45:35Z TRACE hyper::client::pool] pool dropped, dropping pooled (("unix", 2f7661722f72756e2f646f636b65722e736f636b:0))
[2024-01-25T11:45:35Z TRACE prevant::apps] Dropped guard for Some("test")
[2024-01-25T11:45:35Z ERROR prevant::apps::routes] Internal server error: Cannot interact with infrastructure: Docker Error: invalid type: null, expected a sequence at line 1 column 242
[2024-01-25T11:45:35Z INFO  rocket::server::_] Outcome: Success(500 Internal Server Error)
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::dispatch] client tx closed
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] State::close_read()
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] State::close_write()
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
[2024-01-25T11:45:35Z TRACE hyper::proto::h1::conn] shut down IO complete
[2024-01-25T11:45:35Z DEBUG rocket::server] sending response: Response {
        status: 500,
        version: HTTP/1.1,
        headers: {
            "content-type": "application/problem+json",
            "server": "Rocket",
            "x-content-type-options": "nosniff",
            "x-frame-options": "SAMEORIGIN",
            "permissions-policy": "interest-cohort=()",
            "content-length": "207",
        },
        body: Body(
            Streaming,
        ),
    }
```

### PR DESCRIPTION
**Pull request by samuchila**
Currently docker's latest engine v25 is incompatible with ShipLift Crate. Moreover the maintenance for ShipLift has been stopped for a long time. This PR aims to replace ShipLift with the crate Bollard that is being maintained on a regular basis.

Fixes #160

### CODE REVIEW

File: api/src/infrastructure/docker.rs [hunk 1]
```diff
@@ -202,53 +221,63 @@ impl DockerInfrastructure {
...
+                    },
+                )
+                .await?
         }
 
         Ok(())
     }
 
-    async fn delete_network(&self, app_name: &String) -> Result<(), ShipLiftError> {
+    async fn delete_network(&self, app_name: &String) -> Result<(), BollardError> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:251]: Nitpick:

```suggestion
    async fn delete_network(&self, app_name: &AppName) -> Result<(), BollardError> {
```

File: api/src/infrastructure/docker.rs [hunk 2]
```diff
@@ -202,53 +221,63 @@ impl DockerInfrastructure {
         Ok(())
     }
 
-    async fn disconnect_traefik(&self, network_id: &String) -> Result<(), ShipLiftError> {
-        let docker = Docker::new();
-
+    async fn disconnect_traefik(&self, network_id: &String) -> Result<(), BollardError> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:224]: Nitpick:

```suggestion
    async fn disconnect_traefik(&self, network_id: &str) -> Result<(), BollardError> {
```

File: api/src/infrastructure/docker.rs [hunk 3]
```diff
@@ -164,35 +175,43 @@ impl DockerInfrastructure {
...
-        );
+        debug!("Created network for app {} with id {network_id}", app_name);
 
-        Ok(network_create_info.id)
+        Ok(network_id)
     }
 
-    async fn connect_traefik(&self, network_id: &String) -> Result<(), ShipLiftError> {
-        let docker = Docker::new();
+    async fn connect_traefik(&self, network_id: &String) -> Result<(), BollardError> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:192]: Nitpick:

```suggestion
    async fn connect_traefik(&self, network_id: &str) -> Result<(), BollardError> {
```

File: api/src/infrastructure/docker.rs [hunk 4]
```diff
@@ -125,37 +134,39 @@ impl DockerInfrastructure {
...
+                    labels: Some(labels),
+                    ..Default::default()
+                },
+            )
+            .await?;
+        Ok(docker.inspect_container(&container_info.id, None).await?)
     }
 
-    async fn create_or_get_network_id(&self, app_name: &String) -> Result<String, ShipLiftError> {
+    async fn create_or_get_network_id(&self, app_name: &String) -> Result<String, BollardError> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:158]: Nitpick:

```suggestion
    async fn create_or_get_network_id(&self, app_name: &AppName) -> Result<String, BollardError> {
```

File: api/src/infrastructure/docker.rs [hunk 5]
```diff
@@ -164,35 +175,43 @@ impl DockerInfrastructure {
...
-        let docker = Docker::new();
+    async fn connect_traefik(&self, network_id: &String) -> Result<(), BollardError> {
+        let docker = Docker::connect_with_socket_defaults()?;
 
         let containers = docker
-            .containers()
-            .list(&ContainerListOptions::builder().build())
+            .list_containers(Some(ListContainersOptions::<&str> {
+                all: true,
+                filters: HashMap::from([("label", vec!["org.opencontainers.image.title=Traefik"])]),
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:198]: That is new. Are we sure that Traefik 1.7 has this label? (unfortunately, Docker depends still on 1.7, see #23)

File: api/src/infrastructure/docker.rs [hunk 6]
```diff
@@ -202,53 +221,63 @@ impl DockerInfrastructure {
...
 
         Ok(())
     }
 
-    async fn delete_volume_mount(&self, app_name: &String) -> Result<(), ShipLiftError> {
-        let docker = Docker::new();
-        let docker_volumes = docker.volumes();
-        for volume in DockerInfrastructure::fetch_existing_volumes(app_name).await? {
-            docker_volumes.get(&volume.name).delete().await?
+    async fn delete_volume_mount(&self, app_name: &String) -> Result<(), BollardError> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:270]: Nitpick:

```suggestion
    async fn delete_volume_mount(&self, app_name: &AppName) -> Result<(), BollardError> {
```

File: api/src/infrastructure/docker.rs [hunk 7]
```diff
@@ -286,30 +316,40 @@ impl DockerInfrastructure {
...
-            let container = container?;
-            trace!("Deleted container {:?}", container);
+        let mut futures = container_details
+            .into_iter()
+            .map(|details| async {
+                let id = details
+                    .id
+                    .clone()
+                    .expect("id is mandatory for a docker container");
+                docker.stop_container(&id, None).await?;
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:340]: Previously, there was filtering on the state `.filter(|details| details.state.running)` before stopping (a container might be stopped in the UI before deleting the app).

File: api/src/infrastructure/docker.rs [hunk 8]
```diff
@@ -325,11 +365,9 @@ impl DockerInfrastructure {
         network_id: &String,
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:365]: NItpick: 

```suggestion
        network_id: &str,
```

File: api/src/infrastructure/docker.rs [hunk 9]
```diff
@@ -393,110 +456,131 @@ impl DockerInfrastructure {
...
-        if let Some(env) = service_config.env() {
-            let variables = env
-                .iter()
-                .map(|e| format!("{}={}", e.key(), e.value().unsecure()))
-                .collect::<Vec<String>>();
-
-            options.env(variables.iter().map(|s| s.as_str()).collect::<Vec<&str>>());
-        }
+    fn create_container_options<'a>(
+        app_name: &'a str,
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:508]:
```suggestion
        app_name: &'a AppName,
```

File: api/src/infrastructure/docker.rs [hunk 10]
```diff
@@ -508,72 +592,75 @@ impl DockerInfrastructure {
...
-                .into_iter()
-                .filter(|s| {
-                    s.labels
-                        .as_ref()
-                        .map(|label| label.get(APP_NAME_LABEL) == Some(app_name))
-                        .unwrap_or(false)
-                })
-                .collect::<Vec<VolumeInfo>>()
-        })
+    async fn fetch_existing_volumes(app_name: &String) -> Result<VolumeListResponse, BollardError> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:613]:
```suggestion
    async fn fetch_existing_volumes(app_name: &AppName) -> Result<VolumeListResponse, BollardError> {
```

File: api/src/infrastructure/docker.rs [hunk 11]
```diff
@@ -884,13 +1026,41 @@ impl Infrastructure for DockerInfrastructure {
 
                 match status {
                     ServiceStatus::Running => {
-                        if !details.state.running {
-                            run_future_and_map_err!(c.start(), "Could not start container: {}");
+                        if !details
+                            .state
+                            .as_ref()
+                            .map(|state| state.running.unwrap())
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:1032]: Hm... I'm a bit worried about these unwraps. Can we avoid them?

File: api/src/infrastructure/docker.rs [hunk 12]
```diff
@@ -986,55 +1169,108 @@ fn find_port(
...
+                .flatten()
+                .unwrap_or(80u16))
+        } else {
+            Ok(80u16)
+        }
     }
 }
 
-impl TryFrom<&ContainerDetails> for Service {
+impl TryFrom<&ContainerInspectResponse> for Service {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:1197]: In [my attempt](https://github.com/aixigo/PREvant/compare/master...replace-shiplift-with-bollard#diff-a9cc29c6f0841bd26edea1d6302aa4132b47529f46427c58af5f47865650fe1fR1011) I made this `TryFrom` more idiomatic and have less allocations. Please, check that out and merge our attempt. Also, it doesn't require ` let default_labels = HashMap::new();`

**Review by schrieveslaach — CHANGES_REQUESTED** [review]
Looking very promising thanks a lot of tackling it. There are mostly some nitpicks but some things require some more thinking.

File: api/src/infrastructure/docker.rs (hunk 5 above)
Comment (samuchila) [reply api/src/infrastructure/docker.rs:201]: I will do some further digging around and confirm from the official image if these labels are always present across versions. My traefik 1.7 local container did contain this label, hence the approach.

File: api/src/infrastructure/docker.rs (hunk 7 above)
Comment (samuchila) [reply api/src/infrastructure/docker.rs:343]: At line 320-324, I only do a fetch of containers that are running. Anyways I will confirm this with a manual test.
```rust
let container_details = match self
            .get_container_details(
                Some(app_name),
                None,
                Some(ContainerStateStatusEnum::RUNNING),
            )
            .await?
```

File: api/src/infrastructure/docker.rs (hunk 11 above)
Comment (samuchila) [reply api/src/infrastructure/docker.rs:1037]: `unwrap_or_default()` will make better sense here.

File: api/src/infrastructure/docker.rs (hunk 12 above)
Comment (samuchila) [reply api/src/infrastructure/docker.rs:1202]: I somehow missed this. I was going to type you a long message to understand how we can improve this.
I will understand and merge them.

File: api/src/infrastructure/docker.rs (hunk 7 above)
Comment (schrieveslaach) [reply api/src/infrastructure/docker.rs:343]: then you won't delete containers that have been “paused” in the UI.

File: api/src/infrastructure/docker.rs (hunk 5 above)
Comment (samuchila) [reply api/src/infrastructure/docker.rs:201]: Using image title is a hardcode, there are chances it will change with version.
Another option is to use filter `ancestor` with image name. However this does not support partial match i.e `traefik:v1.7-alpine` is the only valid match. So again version dependency.
A manual find is the best approach, i will revert to original.

File: api/src/infrastructure/docker.rs [hunk 13]
```diff
@@ -128,130 +142,149 @@ impl DockerInfrastructure {
...
 
-    async fn disconnect_traefik(&self, network_id: &String) -> Result<(), ShipLiftError> {
-        let docker = Docker::new();
-
+    async fn disconnect_traefik(&self, network_id: &str) -> Result<(), BollardError> {
+        let docker = Docker::connect_with_socket_defaults()?;
         let containers = docker
-            .containers()
-            .list(&ContainerListOptions::builder().build())
+            .list_containers(Some(ListContainersOptions::<&str> {
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:232]: during connecting the containers there is usage of `all` options. Shouldn't we use that here as well?

File: api/src/infrastructure/docker.rs [hunk 14]
```diff
@@ -128,130 +142,149 @@ impl DockerInfrastructure {
...
     }
 
-    async fn delete_volume_mount(&self, app_name: &String) -> Result<(), ShipLiftError> {
-        let docker = Docker::new();
-        let docker_volumes = docker.volumes();
-        for volume in DockerInfrastructure::fetch_existing_volumes(app_name).await? {
-            docker_volumes.get(&volume.name).delete().await?
+    async fn delete_volume_mount(&self, app_name: &AppName) -> Result<(), BollardError> {
+        let docker = Docker::connect_with_socket_defaults()?;
+        for volume in DockerInfrastructure::fetch_existing_volumes(app_name)
```
Comment (schrieveslaach) [inline api/src/infrastructure/docker.rs:279]: Nitpick:

```suggestion
        for volume in Self::fetch_existing_volumes(app_name)
```

**Review by schrieveslaach — CHANGES_REQUESTED** [review]
Some minor commets, please check it out.

File: api/src/infrastructure/docker.rs (hunk 13 above)
Comment (samuchila) [reply api/src/infrastructure/docker.rs:232]: Agreed. In shiplift too the default build option is `all`.

Comment (samuchila) [reply api/src/infrastructure/docker.rs]: There should have been no `all` at both sides. Now its in-line with prior shiplift implementation.
```rust
async fn connect_traefik(&self, network_id: &String) -> Result<(), ShipLiftError> {
        let docker = Docker::new();

        let containers = docker
            .containers()
            .list(&ContainerListOptions::builder().build())
            .await?;
```

**Review by schrieveslaach — APPROVED** [review]
